<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>C:\m@ngas\TEMAT\romy\project\c#\temp\TheMaxt.Library\TheMaxt.SqlData.Standard\TheMaxt.SqlData.Standard.xml</DocumentationFile>
  </PropertyGroup>

</Project>
